"""empty message

Revision ID: 35db71814511
Revises: None
Create Date: 2016-09-12 10:43:22.946197

"""

# revision identifiers, used by Alembic.
revision = '35db71814511'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mascota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('propietario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['propietario_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascota')
    op.drop_table('persona')
    ### end Alembic commands ###
