"""empty message

Revision ID: 7d18cbbf03e5
Revises: b1151ce51e21
Create Date: 2016-09-12 11:49:43.626426

"""

# revision identifiers, used by Alembic.
revision = '7d18cbbf03e5'
down_revision = 'b1151ce51e21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('rfid', sa.String(length=20), nullable=True),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['orden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encargado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('rfid', sa.String(length=20), nullable=True),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['orden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encargado')
    op.drop_table('empleado')
    ### end Alembic commands ###
