"""empty message

Revision ID: b1151ce51e21
Revises: None
Create Date: 2016-09-12 11:42:47.611790

"""

# revision identifiers, used by Alembic.
revision = 'b1151ce51e21'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pieza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=20), nullable=True),
    sa.Column('rfid', sa.String(length=20), nullable=True),
    sa.Column('vol', sa.Integer(), nullable=True),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['orden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pieza')
    op.drop_table('orden')
    ### end Alembic commands ###
